- name: ensure keystone database is present
  mysql_db: name=keystone

- name: ensure keystone database user is present
  mysql_user: >
    name=keystone host={{ item }}
    password={{ keystone_db_password }}
    priv=keystone.*:ALL
  with_items:
    - "{{ controller_ip }}"
    - 127.0.0.1
    - localhost
    - ::1

- name: ensure glance database is present
  mysql_db: name=glance

- name: ensure glance database user is present
  mysql_user: >
    name=glance
    host={{ item }}
    password={{ glance_db_password }}
    priv=glance.*:ALL
  with_items:
    - "{{ controller_ip }}"
    - "{{ storage_ip }}"
    - 127.0.0.1
    - localhost
    - ::1

- name: ensure cinder database is present
  mysql_db: name=cinder

- name: ensure cinder database user is present
  mysql_user: >
    name=cinder
    host={{ item }}
    password={{ cinder_db_password }}
    priv=cinder.*:ALL
  with_items:
    - "{{ controller_ip }}"
    - 127.0.0.1
    - localhost
    - ::1

- name: ensure nova database is present
  mysql_db: name=nova

# create nova-api, nova_cell0

- name: ensure nova_api database is present
  mysql_db: name=nova_api

- name: ensure nova_cell0 database is present
  mysql_db: name=nova_cell0

- name: ensure nova database user is present
  mysql_user: >
    name=nova
    host={{ item }}
    password={{ nova_db_password }}
    priv=nova.*:ALL/nova_api.*:ALL/nova_cell0.*:ALL
  with_items:
    - '%'
    - localhost
      

- name: ensure neutron database is present
  mysql_db: name=neutron
    
- name: ensure neutron database user is present
  mysql_user: >
    name=neutron
    host={{ item }}
    password={{ neutron_db_password }}
    priv=neutron.*:ALL
  with_items:
    - "{{ controller_ip }}"
    - 127.0.0.1
    - localhost
    - ::1
